# Generated by Django 4.2.3 on 2023-08-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_cabello_ciudadocorporal_clientes_maquillaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidadocorporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField()),
                ('Nombre', models.CharField(max_length=50)),
                ('Sexo', models.CharField(max_length=50)),
                ('Precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Ciudadocorporal',
        ),
        migrations.AddField(
            model_name='cabello',
            name='Precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='maquillaje',
            name='Precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='perfumeria',
            name='Precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
