# Generated by Django 4.2.3 on 2023-09-25 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_cabellopermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CabelloPermission',
        ),
    ]
